### ISSUE TITLE
influence(influencee, influencer, identifier=None, other_attributes=None) causes "TypeError: 'NoneType' object is not callable"

### ISSUE THREAD

**Issue by MaWi54321** [DLR-SC/prov-db-connector#79]
Hello,
i tried to call the prov influence in combination of agent, entity and activity with all possible combination. The result was a TypeError: 'NoneType' object is not callable.

Traceback (most recent call last):
  File "c:\Users\..\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\..\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\..\.vscode\extensions\ms-python.python-2019.9.34911\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\dev\..\ProvDBConnector\prov_model_test1.py", line 199, in <module>
    document_id = prov_api.save_document(prov_document)
  File "C:\Anaconda3\lib\site-packages\provdbconnector\prov_db.py", line 162, in save_document
    doc_id = self._save_bundle_internal(prov_document)
  File "C:\Anaconda3\lib\site-packages\provdbconnector\prov_db.py", line 503, in _save_bundle_internal
    self.save_relation(relation, bundle_id)
  File "C:\Anaconda3\lib\site-packages\provdbconnector\prov_db.py", line 563, in save_relation
    self.save_element(prov_element=from_type_cls(prov_relation.bundle, identifier=from_qualified_name), bundle_id=bundle_id)
TypeError: 'NoneType' object is not callable

Python: 3.7.1
prov-db-connector: 0.3.1
prov: 1.5.2 / 1.5.3

**Comment by B-Stefan** [comment]
@StarfighterV Thanks for reporting this issue. 

Could you post an example that produces this error? Just a simple snippet :)

**Comment by MaWi54321** [comment]
Sorry for the late answer - here is a simple snippet. I hope it helps a little:

pd = ProvDocument()
pd.add_namespace("ex", "ex/")
pd.entity(identifier="ex:test1")
pd.entity(identifier="ex:test2")
pd.influence(influencee="ex:test1",influencer="ex:test2")
document_id = prov_api.save_document(pd)


Error:
Traceback (most recent call last):
  File "c:\Users\..\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\..\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\..\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\..\.conda\envs\provenance\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\..\.conda\envs\provenance\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\..\.conda\envs\provenance\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\dev\Python\Provenanve\ProvDBConnector\prov_model_Widerstandschweissen.py", line 125, in <module>
    document_id = prov_api.save_document(pd)
  File "C:\Users\..\.conda\envs\provenance\lib\site-packages\provdbconnector\prov_db.py", line 162, in save_document
    doc_id = self._save_bundle_internal(prov_document)
  File "C:\Users\..\.conda\envs\provenance\lib\site-packages\provdbconnector\prov_db.py", line 503, in _save_bundle_internal
    self.save_relation(relation, bundle_id)
  File "C:\Users\..\.conda\envs\provenance\lib\site-packages\provdbconnector\prov_db.py", line 563, in save_relation
    self.save_element(prov_element=from_type_cls(prov_relation.bundle, identifier=from_qualified_name), bundle_id=bundle_id)
TypeError: 'NoneType' object is not callable

**Comment by B-Stefan** [comment]
Don't worry! Thanks for the information. 
I will look into this on the Weekend!

**Comment by B-Stefan** [comment]
Ref: #83

**Comment by B-Stefan** [comment]
@StarfighterV  Solved see: https://github.com/DLR-SC/prov-db-connector/blob/master/examples/simple_example_influence.py
